app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    defaults:
        _format: json

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /doc