# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    problem.response_factory:
        class: AppBundle\Problem\ResponseFactory

    exception_subscriber:
            class: AppBundle\EventListener\ExceptionSubscriber
            arguments: ['%kernel.debug%', '@problem.response_factory', '@logger']
            tags:
                - { name: kernel.event_subscriber }
